dev:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT_FOOTBALL') }}"
      password: "{{ env_var('DBT_PASSWORD_FOOTBALL') }}"

      user: DEV_DBTFOOTBALL
      role: DBT_PROD
      database: DEV_DBT_FOOTBALL
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 4
    
prod:
  target: prod 
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT_FOOTBALL') }}"
      password: "{{ env_var('DBT_PASSWORD_FOOTBALL') }}"

      user: DBTFOOTBALL
      role: DBT_PROD
      database: PROD_DBT_FOOTBALL
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 4


