name: DBT deploy prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab  
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ./profiles/
  DBT_ACCOUNT_FOOTBALL: ${{ secrets.DBT_ACCOUNT_FOOTBALL }}
  DBT_PASSWORD_FOOTBALL: ${{ secrets.DBT_PASSWORD_FOOTBALL }}

jobs:

# This workflow contains a single job called "build-dbt"
  deploy_to_production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:

      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install Docker
        run:  |
          python -m pip install --upgrade pip
          pip install docker
    
      - name: Docker Log IN
        run: docker login -u alessandro19920610 -p ${{ secrets.DBT_DOCKER }}

      - name: Pull Docker Image developmemt
        run: docker pull alessandro19920610/dbt-image-artifacts
      
      - name: New docker Image for development
        run: docker tag alessandro19920610/dbt-image-development alessandro19920610/dbt-image-production

      - name: Push Image
        run: docker push alessandro19920610/dbt-image-production
      