name: Deploy to Production

on:
  workflow_dispatch:
    branches: [main]

env:
  DBT_PROFILES_DIR: ./profiles/
  DBT_ACCOUNT_FOOTBALL: ${{ secrets.DBT_ACCOUNT_FOOTBALL }}
  DBT_PASSWORD_FOOTBALL: ${{ secrets.DBT_PASSWORD_FOOTBALL }}

jobs:
  deployment_production:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      - name: Get Dependencies
        run: dbt deps 

      - name: Generate Files
        run: dbt compile --profiles-dir profiles --profile dev
