name: Run DBT in DOCKER build for DEV

  # Allows you to run this workflow manually from the Actions tab  
on:
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ./profiles/
  DBT_ACCOUNT_FOOTBALL: ${{ secrets.DBT_ACCOUNT_FOOTBALL }}
  DBT_PASSWORD_FOOTBALL: ${{ secrets.DBT_PASSWORD_FOOTBALL }}
  DBT_COMMANDS: dbt run --profile dev

jobs:
  dbt_build_dev:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install Docker
        run:  |
          python -m pip install --upgrade pip
          pip install docker
    
      - name: Docker Log IN
        run: docker login -u alessandro19920610 -p ${{ secrets.DBT_DOCKER }}

      - name: Pull Docker Image developmemt
        run: docker pull alessandro19920610/dbt-image-development

      - name: Run docker container
        run: docker run \
          --env DBT_ACCOUNT_FOOTBALL="${DBT_ACCOUNT_FOOTBALL}" \
          --env DBT_PASSWORD_FOOTBALL="${DBT_PASSWORD_FOOTBALL}" \
          alessandro19920610/dbt-image-development \
          /bin/bash -c "${DBT_COMMANDS}" 