name: DBT Load Artifacts

# Controls when the workflow will run
on:
  # Triggers the workflow when pull request events are closed in the "main" branch
  pull_request:
    types:
      - closed
    branches: [main]

  # Allows manual triggering of the workflow from the Actions tab  
  workflow_dispatch:

env:
  # Specifies the directory containing DBT profiles
  DBT_PROFILES_DIR: ./profiles/
  # Secret variables for DBT account authentication
  DBT_ACCOUNT_FOOTBALL: ${{ secrets.DBT_ACCOUNT_FOOTBALL }}
  DBT_PASSWORD_FOOTBALL: ${{ secrets.DBT_PASSWORD_FOOTBALL }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "load-dbt-artifacts"
  load-dbt-artifacts:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dbt-snowflake
      - name: Install dbt-snowflake
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake
      
      # Install DBT dependencies
      - name: Install DBT dependencies
        run: dbt deps
          
      # Run dbt compile to compile SQL files
      - name: Run dbt compile 
        run: dbt compile --profiles-dir profiles --profile dev --target-path=dbt-artifact-directory && ls

      # Upload compiled DBT artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-artifacts-files
          path: dbt-artifact-directory/
      
      # Check if the artifacts are uploaded by listing the contents of the artifact directory
      - name: Check Artifacts are uploaded
        run: ls
