name: GitHub DBT CI/CD

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'What is the reason to trigger this manually?'
        # Default value if no value is explicitly provided
        default: 'workflow test'
        # Input has to be provided for the workflow to run
        required: true



   
jobs:
  run_dbt_dev:
    name: run_from_github

    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Get check connection to snowflake
        run: dbt debug 
      
      - name: Get dependencies # ok guess I need this anyway
        run: dbt deps 

      - name: Run dbt build
        run: dbt run
# This is a basic workflow to help you get started with Actions

name: DBT CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ./profiles/
  DBT_USER_FOOTBALL: ${{ secrets.DBT_USER_FOOTBALL }}
  DBT_PASSWORD_FOOTBALL: ${{ secrets.DBT_PASSWORD_FOOTBALL }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get check connection to snowflake
        run: dbt debug 
      
      - name: Get dependencies # ok guess I need this anyway
        run: dbt deps 

      - name: Run dbt build
        run: dbt run